# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ffff.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1083, 709)
        MainWindow.setMouseTracking(True)
        MainWindow.setIconSize(QtCore.QSize(23, 23))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(981, 551))
        self.frame.setStyleSheet("#frame{\n"
" background:url(:/新前缀/背景.png);\n"
" border-radius:15px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_top = QtWidgets.QFrame(self.frame)
        self.frame_top.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(36,38,58);\n"
"    border-top-left-radius:15px;\n"
"    border-top-right-radius:15px;\n"
"}")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_5.setContentsMargins(9, 9, -1, 9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_logo = QtWidgets.QLabel(self.frame_top)
        self.label_logo.setMinimumSize(QtCore.QSize(100, 0))
        self.label_logo.setStyleSheet("image: url(:/新前缀/logo.png);")
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout_5.addWidget(self.label_logo, 0, QtCore.Qt.AlignLeft)
        self.frame_close = QtWidgets.QFrame(self.frame_top)
        self.frame_close.setStyleSheet("QFrame{\n"
"border:none;\n"
"}")
        self.frame_close.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_close.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_close.setObjectName("frame_close")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_close)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_min = QtWidgets.QPushButton(self.frame_close)
        self.pushButton_min.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_min.setMaximumSize(QtCore.QSize(16777215, 500))
        self.pushButton_min.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_min.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/图标/最小化2-02.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min.setIcon(icon)
        self.pushButton_min.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_min.setObjectName("pushButton_min")
        self.horizontalLayout_4.addWidget(self.pushButton_min)
        self.pushButton_max = QtWidgets.QPushButton(self.frame_close)
        self.pushButton_max.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_max.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_max.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/图标/24.全屏_最大化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_max.setIcon(icon1)
        self.pushButton_max.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_max.setObjectName("pushButton_max")
        self.horizontalLayout_4.addWidget(self.pushButton_max)
        self.pushButton_close = QtWidgets.QPushButton(self.frame_close)
        self.pushButton_close.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_close.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"padding-bottom:5px;\n"
"}")
        self.pushButton_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/图标/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon2)
        self.pushButton_close.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_4.addWidget(self.pushButton_close)
        self.horizontalLayout_5.addWidget(self.frame_close, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_15.addWidget(self.frame_top)
        self.frame_down = QtWidgets.QFrame(self.frame)
        self.frame_down.setObjectName("frame_down")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_down)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_choice = QtWidgets.QFrame(self.frame_down)
        self.frame_choice.setMinimumSize(QtCore.QSize(152, 0))
        self.frame_choice.setStyleSheet("QFrame{\n"
"    background-color: rgb(36, 38, 58);\n"
"    border-bottom-left-radius:15px;\n"
"}")
        self.frame_choice.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_choice.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_choice.setObjectName("frame_choice")
        self.pushButton_view = QtWidgets.QPushButton(self.frame_choice)
        self.pushButton_view.setGeometry(QtCore.QRect(10, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.pushButton_view.setFont(font)
        self.pushButton_view.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color:rgb(255,255,255);\n"
"    border-radius:5px;\n"
"    border:none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(29,30,44);\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(29,30,44);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/图标/显示.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_view.setIcon(icon3)
        self.pushButton_view.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_view.setCheckable(True)
        self.pushButton_view.setChecked(True)
        self.pushButton_view.setAutoExclusive(True)
        self.pushButton_view.setObjectName("pushButton_view")
        self.pushButton_settings = QtWidgets.QPushButton(self.frame_choice)
        self.pushButton_settings.setGeometry(QtCore.QRect(10, 60, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.pushButton_settings.setFont(font)
        self.pushButton_settings.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color:rgb(255,255,255);\n"
"    border-radius:5px;\n"
"    border:none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(29,30,44);\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(29,30,44);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/图标/设置2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_settings.setIcon(icon4)
        self.pushButton_settings.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_settings.setCheckable(True)
        self.pushButton_settings.setChecked(False)
        self.pushButton_settings.setAutoExclusive(True)
        self.pushButton_settings.setObjectName("pushButton_settings")
        self.horizontalLayout_14.addWidget(self.frame_choice)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_down)
        self.stackedWidget.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_view = QtWidgets.QWidget()
        self.page_view.setObjectName("page_view")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.page_view)
        self.horizontalLayout_12.setContentsMargins(30, 22, 18, 18)
        self.horizontalLayout_12.setSpacing(30)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.treeView = QtWidgets.QTreeView(self.page_view)
        self.treeView.setMinimumSize(QtCore.QSize(256, 603))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        self.treeView.setFont(font)
        self.treeView.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.treeView.setStyleSheet("QTreeView {\n"
"    alternate-background-color: red;\n"
"    color:white;\n"
"margin-bottom:3px;\n"
"margin-top:4px;\n"
"border:2px solid;\n"
"    border-color: rgb(5, 32, 56);\n"
"border-radius:10px;\n"
"}\n"
"QHeaderView::section{\n"
"    border:none;\n"
"    border-radius-top-left:10px;\n"
"    border-radius-top-right:10px;\n"
"    font: 75 12pt \"Microsoft YaHei UI\";\n"
"    color:#598FDC;\n"
"    background-color: rgb(36, 38, 58);\n"
"}\n"
"\n"
"QScrollBar:vertical{width:8px;\n"
"         background:transparent;\n"
"margin:0px,1px,0px,1px;\n"
"    padding-top:0px;\n"
"padding-bottom:0px;\n"
"border-radius:4px;}\n"
"QScrollBar::handle:vertical{\n"
"background:rgb(61,67,79);\n"
"   border-radius:4px;}\n"
"QScrollBar::handle:vertical:hover{\n"
"background:rgb(212,216,228);\n"
"border-radius:4px;}\n"
"QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical{\n"
"background:transparent;\n"
"border-radius:4px;}/*设置滑块滑动后一端槽的背景透明*/\n"
"QScrollBar::add-line:vertical,QScrollBar::sub-line:vertical{\n"
" height:0px;width:0px;};/*去掉上下箭头*/\n"
"")
        self.treeView.setObjectName("treeView")
        self.treeView.header().setMinimumSectionSize(30)
        self.horizontalLayout_12.addWidget(self.treeView)
        self.frame_animation = QtWidgets.QFrame(self.page_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_animation.sizePolicy().hasHeightForWidth())
        self.frame_animation.setSizePolicy(sizePolicy)
        self.frame_animation.setStyleSheet("QFrame{\n"
"    background-color: rgb(36,38,58);\n"
"    border-radius:10px;\n"
"}")
        self.frame_animation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_animation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_animation.setObjectName("frame_animation")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_animation)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.frame_animation)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_animation)
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal { \n"
"    border: 1px solid gray;\n"
"    height: 2px; \n"
"    left: 8px; \n"
"    right: 8px; \n"
"} \n"
"\n"
"QSlider::handle:horizontal { \n"
"    border: 1px solid gray; \n"
"    background:white;\n"
"    border-radius: 5px;\n"
"    width: 10px; \n"
"    height: 10px; \n"
"    margin: -5px; \n"
"} \n"
"\n"
"QSlider::add-page:horizontal{ \n"
"    background: rgb(189, 189, 189); \n"
"} \n"
"QSlider::sub-page:horizontal{ \n"
"    background: rgb(80, 165, 245); \n"
"}\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_10.addWidget(self.horizontalSlider)
        self.frame_vedio = QtWidgets.QFrame(self.frame_animation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_vedio.sizePolicy().hasHeightForWidth())
        self.frame_vedio.setSizePolicy(sizePolicy)
        self.frame_vedio.setObjectName("frame_vedio")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_vedio)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label = QtWidgets.QLabel(self.frame_vedio)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"border: 0px solid;\n"
"border-color: #598FDC;\n"
"background-color:rgba(0,0,0,0);\n"
"color:white;\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_17.addWidget(self.label)
        self.pushButton_back = QtWidgets.QPushButton(self.frame_vedio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_back.sizePolicy().hasHeightForWidth())
        self.pushButton_back.setSizePolicy(sizePolicy)
        self.pushButton_back.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setStyleSheet("QPushButton {    \n"
"    border: 0px solid;\n"
"    border-color: #598FDC;\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(38, 43, 85);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: transparent;\n"
"}")
        self.pushButton_back.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/图标/快退.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_back.setIcon(icon5)
        self.pushButton_back.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout_17.addWidget(self.pushButton_back)
        self.pushButton_stop = QtWidgets.QPushButton(self.frame_vedio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_stop.sizePolicy().hasHeightForWidth())
        self.pushButton_stop.setSizePolicy(sizePolicy)
        self.pushButton_stop.setMinimumSize(QtCore.QSize(70, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setStyleSheet("QPushButton {    \n"
"    border: 0px solid;\n"
"    border-color: #598FDC;\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(38, 43, 85);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: transparent;\n"
"}")
        self.pushButton_stop.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/图标/24gf-pause2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_stop.setIcon(icon6)
        self.pushButton_stop.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout_17.addWidget(self.pushButton_stop)
        self.pushButton_forward = QtWidgets.QPushButton(self.frame_vedio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_forward.sizePolicy().hasHeightForWidth())
        self.pushButton_forward.setSizePolicy(sizePolicy)
        self.pushButton_forward.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_forward.setFont(font)
        self.pushButton_forward.setStyleSheet("QPushButton {    \n"
"    border: 0px solid;\n"
"    border-color: #598FDC;\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(38, 43, 85);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: transparent;\n"
"}")
        self.pushButton_forward.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/图标/快进.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/图标/快进.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.pushButton_forward.setIcon(icon7)
        self.pushButton_forward.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_forward.setObjectName("pushButton_forward")
        self.horizontalLayout_17.addWidget(self.pushButton_forward)
        self.label_3 = QtWidgets.QLabel(self.frame_vedio)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_17.addWidget(self.label_3)
        self.verticalLayout_10.addWidget(self.frame_vedio)
        spacerItem = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem)
        self.horizontalLayout_12.addWidget(self.frame_animation)
        self.stackedWidget.addWidget(self.page_view)
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setObjectName("page_settings")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.page_settings)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_settingleft = QtWidgets.QFrame(self.page_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_settingleft.sizePolicy().hasHeightForWidth())
        self.frame_settingleft.setSizePolicy(sizePolicy)
        self.frame_settingleft.setMinimumSize(QtCore.QSize(231, 411))
        self.frame_settingleft.setObjectName("frame_settingleft")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_settingleft)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, 10, -1, -1)
        self.gridLayout.setHorizontalSpacing(30)
        self.gridLayout.setVerticalSpacing(25)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_nodeset = QtWidgets.QFrame(self.frame_settingleft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_nodeset.sizePolicy().hasHeightForWidth())
        self.frame_nodeset.setSizePolicy(sizePolicy)
        self.frame_nodeset.setMinimumSize(QtCore.QSize(231, 0))
        self.frame_nodeset.setStyleSheet("QFrame{\n"
" border:2px solid;\n"
"    border-color: rgb(5, 32, 56);\n"
"    background-color: rgb(36,38,58);\n"
"border-radius:10px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"outline: 0px solid gray;            \n"
"/*border:1px solid #eeeeee;*/            \n"
"color:rgb(145,151,163);\n"
"selection-color:white;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei UI;            \n"
"background-color:rgb(18,26,39);\n"
"selection-background-color:rgb(33,41,54);\n"
"border-top-radius:0px;\n"
"border-bottom-radius:10px;\n"
"}")
        self.frame_nodeset.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_nodeset.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_nodeset.setObjectName("frame_nodeset")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_nodeset)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_node = QtWidgets.QLabel(self.frame_nodeset)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_node.sizePolicy().hasHeightForWidth())
        self.label_node.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_node.setFont(font)
        self.label_node.setStyleSheet("QLabel{\n"
"border:none;\n"
"color:#598FDC;\n"
"}")
        self.label_node.setObjectName("label_node")
        self.verticalLayout_7.addWidget(self.label_node, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.frame_selectnode = QtWidgets.QFrame(self.frame_nodeset)
        self.frame_selectnode.setStyleSheet("border:none;\n"
"")
        self.frame_selectnode.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_selectnode.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_selectnode.setObjectName("frame_selectnode")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_selectnode)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_7.addWidget(self.frame_selectnode)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_nodeset)
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"border:none;\n"
"background-color:transparent;\n"
"}\n"
"QScrollArea QScrollBar:vertical{width:8px;\n"
"         background:transparent;\n"
"margin:0px,1px,0px,1px;\n"
"    padding-top:0px;\n"
"padding-bottom:0px;\n"
"border-radius:4px;}\n"
"QScrollArea QScrollBar::handle:vertical{\n"
"background:rgb(61,67,79);\n"
"   border-radius:4px;}\n"
"QScrollArea QScrollBar::handle:vertical:hover{\n"
"background:rgb(212,216,228);\n"
"border-radius:4px;}\n"
"QScrollArea QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical{\n"
"background:transparent;\n"
"border-radius:4px;}/*设置滑块滑动后一端槽的背景透明*/\n"
"QScrollArea QScrollBar::add-line:vertical,QScrollBar::sub-line:vertical{\n"
" height:0px;width:0px;};/*去掉上下箭头*/\n"
"")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 247, 326))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_vector = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_vector.sizePolicy().hasHeightForWidth())
        self.pushButton_vector.setSizePolicy(sizePolicy)
        self.pushButton_vector.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_vector.setFont(font)
        self.pushButton_vector.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color:rgb(255,255,255);\n"
"    border-radius:5px;\n"
"    border:none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(29,30,44);\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: #e8ccc7;\n"
"}")
        self.pushButton_vector.setCheckable(True)
        self.pushButton_vector.setChecked(True)
        self.pushButton_vector.setAutoExclusive(False)
        self.pushButton_vector.setObjectName("pushButton_vector")
        self.verticalLayout_9.addWidget(self.pushButton_vector)
        self.pushButton_stack = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_stack.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_stack.setFont(font)
        self.pushButton_stack.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color:rgb(255,255,255);\n"
"    border-radius:5px;\n"
"    border:none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(29,30,44);\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: #e8ccc7;\n"
"}")
        self.pushButton_stack.setCheckable(True)
        self.pushButton_stack.setChecked(False)
        self.pushButton_stack.setAutoExclusive(False)
        self.pushButton_stack.setObjectName("pushButton_stack")
        self.verticalLayout_9.addWidget(self.pushButton_stack)
        self.pushButton_heap = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_heap.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_heap.setFont(font)
        self.pushButton_heap.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color:rgb(255,255,255);\n"
"    border-radius:5px;\n"
"    border:none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(29,30,44);\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: #e8ccc7;\n"
"}")
        self.pushButton_heap.setCheckable(True)
        self.pushButton_heap.setChecked(False)
        self.pushButton_heap.setAutoExclusive(False)
        self.pushButton_heap.setObjectName("pushButton_heap")
        self.verticalLayout_9.addWidget(self.pushButton_heap)
        self.pushButton_tree = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_tree.sizePolicy().hasHeightForWidth())
        self.pushButton_tree.setSizePolicy(sizePolicy)
        self.pushButton_tree.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_tree.setFont(font)
        self.pushButton_tree.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color:rgb(255,255,255);\n"
"    border-radius:5px;\n"
"    border:none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(29,30,44);\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: #e8ccc7;\n"
"}")
        self.pushButton_tree.setCheckable(True)
        self.pushButton_tree.setChecked(False)
        self.pushButton_tree.setAutoExclusive(False)
        self.pushButton_tree.setObjectName("pushButton_tree")
        self.verticalLayout_9.addWidget(self.pushButton_tree)
        self.pushButton_matrix = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_matrix.sizePolicy().hasHeightForWidth())
        self.pushButton_matrix.setSizePolicy(sizePolicy)
        self.pushButton_matrix.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_matrix.setFont(font)
        self.pushButton_matrix.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color:rgb(255,255,255);\n"
"    border-radius:5px;\n"
"    border:none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(29,30,44);\n"
"padding-bottom:5px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: #e8ccc7;\n"
"}")
        self.pushButton_matrix.setCheckable(True)
        self.pushButton_matrix.setChecked(False)
        self.pushButton_matrix.setAutoExclusive(False)
        self.pushButton_matrix.setObjectName("pushButton_matrix")
        self.verticalLayout_9.addWidget(self.pushButton_matrix)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 1677721))
        self.label_4.setStyleSheet("QLabel{\n"
"    border: none;\n"
"background:transparent;\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.gridLayout.addWidget(self.frame_nodeset, 0, 0, 3, 1)
        self.frame_languageset_2 = QtWidgets.QFrame(self.frame_settingleft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_languageset_2.sizePolicy().hasHeightForWidth())
        self.frame_languageset_2.setSizePolicy(sizePolicy)
        self.frame_languageset_2.setMinimumSize(QtCore.QSize(231, 101))
        self.frame_languageset_2.setStyleSheet("QFrame{\n"
" border:2px solid;\n"
"    border-color: rgb(5, 32, 56);\n"
"    background-color: rgb(36,38,58);\n"
"border-radius:10px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"outline: 0px solid gray;            \n"
"/*border:1px solid #eeeeee;*/            \n"
"color:rgb(145,151,163);\n"
"selection-color:white;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei UI;            \n"
"background-color:rgb(18,26,39);\n"
"selection-background-color:rgb(33,41,54);\n"
"border-top-radius:0px;\n"
"border-bottom-radius:10px;\n"
"}")
        self.frame_languageset_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_languageset_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_languageset_2.setObjectName("frame_languageset_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_languageset_2)
        self.verticalLayout_8.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_language_2 = QtWidgets.QLabel(self.frame_languageset_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_language_2.sizePolicy().hasHeightForWidth())
        self.label_language_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_language_2.setFont(font)
        self.label_language_2.setStyleSheet("\n"
"QLabel{\n"
"border:none;\n"
"color:#598FDC;\n"
"}")
        self.label_language_2.setObjectName("label_language_2")
        self.verticalLayout_8.addWidget(self.label_language_2)
        self.frame_selectlan_2 = QtWidgets.QFrame(self.frame_languageset_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_selectlan_2.sizePolicy().hasHeightForWidth())
        self.frame_selectlan_2.setSizePolicy(sizePolicy)
        self.frame_selectlan_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_selectlan_2.setStyleSheet("QFrame{border:none;\n"
"}")
        self.frame_selectlan_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_selectlan_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_selectlan_2.setLineWidth(0)
        self.frame_selectlan_2.setObjectName("frame_selectlan_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_selectlan_2)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.comboBox_yangshi = QtWidgets.QComboBox(self.frame_selectlan_2)
        self.comboBox_yangshi.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_yangshi.sizePolicy().hasHeightForWidth())
        self.comboBox_yangshi.setSizePolicy(sizePolicy)
        self.comboBox_yangshi.setMinimumSize(QtCore.QSize(103, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.comboBox_yangshi.setFont(font)
        self.comboBox_yangshi.setMouseTracking(False)
        self.comboBox_yangshi.setTabletTracking(False)
        self.comboBox_yangshi.setStyleSheet("\n"
"QComboBox {\n"
"    border: 0px solid;\n"
"    border-bottom: 2px solid;\n"
"    border-color: #598FDC;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 1px 10px 1px 3px;\n"
"    min-width: 6em;\n"
"    background-color: rgb(57, 63, 103);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    /*subcontrol-origin: padding;*/\n"
"    subcontrol-position: top right;\n"
"    width: 40px;\n"
"    height: 39px;\n"
"    border: 0px solid;\n"
"    \n"
"    border-radius: 5px; /* same radius as the QComboBox */\n"
"}\n"
"QComboBox::drop-down:pressed,QComboBox::drop-down:hover {\n"
"    background-color: rgb(38, 43, 85);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    image: url(:/图标/下拉选择.png);\n"
"width: 100px;\n"
"height:25px;\n"
"    \n"
"}\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"outline: 0px solid gray;            \n"
"border:0px solid #eeeeee;            \n"
"color:rgb(145,151,163);\n"
"selection-color:white;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei UI;            \n"
"background-color:rgb(18,26,39);\n"
"selection-background-color:rgb(33,41,54);\n"
"}")
        self.comboBox_yangshi.setEditable(False)
        self.comboBox_yangshi.setIconSize(QtCore.QSize(9, 9))
        self.comboBox_yangshi.setObjectName("comboBox_yangshi")
        self.comboBox_yangshi.addItem("")
        self.comboBox_yangshi.setItemText(0, "")
        self.horizontalLayout_9.addWidget(self.comboBox_yangshi)
        self.verticalLayout_8.addWidget(self.frame_selectlan_2, 0, QtCore.Qt.AlignBottom)
        self.gridLayout.addWidget(self.frame_languageset_2, 0, 1, 1, 1)
        self.frame_theme = QtWidgets.QFrame(self.frame_settingleft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_theme.sizePolicy().hasHeightForWidth())
        self.frame_theme.setSizePolicy(sizePolicy)
        self.frame_theme.setMinimumSize(QtCore.QSize(231, 101))
        self.frame_theme.setStyleSheet("QFrame{\n"
" border:2px solid;\n"
"    border-color: rgb(5, 32, 56);\n"
"    background-color: rgb(36,38,58);\n"
"border-radius:10px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"outline: 0px solid gray;            \n"
"/*border:1px solid #eeeeee;*/            \n"
"color:rgb(145,151,163);\n"
"selection-color:white;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei UI;            \n"
"background-color:rgb(18,26,39);\n"
"selection-background-color:rgb(33,41,54);\n"
"border-top-radius:0px;\n"
"border-bottom-radius:10px;\n"
"}")
        self.frame_theme.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_theme.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_theme.setObjectName("frame_theme")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_theme)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_theme = QtWidgets.QLabel(self.frame_theme)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_theme.sizePolicy().hasHeightForWidth())
        self.label_theme.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_theme.setFont(font)
        self.label_theme.setStyleSheet("QLabel{\n"
"border:none;\n"
"color:#598FDC;\n"
"}")
        self.label_theme.setObjectName("label_theme")
        self.verticalLayout_6.addWidget(self.label_theme, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.frame_selecttheme = QtWidgets.QFrame(self.frame_theme)
        self.frame_selecttheme.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_selecttheme.setStyleSheet("QFrame{border:none;\n"
"}")
        self.frame_selecttheme.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_selecttheme.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_selecttheme.setLineWidth(0)
        self.frame_selecttheme.setObjectName("frame_selecttheme")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_selecttheme)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBox_theme = QtWidgets.QComboBox(self.frame_selecttheme)
        self.comboBox_theme.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_theme.sizePolicy().hasHeightForWidth())
        self.comboBox_theme.setSizePolicy(sizePolicy)
        self.comboBox_theme.setMinimumSize(QtCore.QSize(103, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.comboBox_theme.setFont(font)
        self.comboBox_theme.setMouseTracking(False)
        self.comboBox_theme.setTabletTracking(False)
        self.comboBox_theme.setStyleSheet("\n"
"QComboBox {\n"
"    border: 0px solid;\n"
"    border-bottom: 2px solid;\n"
"    border-color: #598FDC;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 1px 10px 1px 3px;\n"
"    min-width: 6em;\n"
"    background-color: rgb(57, 63, 103);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    /*subcontrol-origin: padding;*/\n"
"    subcontrol-position: top right;\n"
"    width: 40px;\n"
"    height: 39px;\n"
"    border: 0px solid;\n"
"    \n"
"    border-radius: 5px; /* same radius as the QComboBox */\n"
"}\n"
"QComboBox::drop-down:pressed,QComboBox::drop-down:hover {\n"
"    background-color: rgb(38, 43, 85);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    image: url(:/图标/下拉选择.png);\n"
"width: 100px;\n"
"height:25px;\n"
"    \n"
"}\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"outline: 0px solid gray;            \n"
"border:0px solid #eeeeee;            \n"
"color:rgb(145,151,163);\n"
"selection-color:white;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei UI;            \n"
"background-color:rgb(18,26,39);\n"
"selection-background-color:rgb(33,41,54);\n"
"}")
        self.comboBox_theme.setEditable(False)
        self.comboBox_theme.setIconSize(QtCore.QSize(9, 9))
        self.comboBox_theme.setObjectName("comboBox_theme")
        self.comboBox_theme.addItem("")
        self.comboBox_theme.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_theme)
        self.verticalLayout_6.addWidget(self.frame_selecttheme, 0, QtCore.Qt.AlignBottom)
        self.gridLayout.addWidget(self.frame_theme, 0, 2, 1, 1)
        self.frame_theme_2 = QtWidgets.QFrame(self.frame_settingleft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_theme_2.sizePolicy().hasHeightForWidth())
        self.frame_theme_2.setSizePolicy(sizePolicy)
        self.frame_theme_2.setMinimumSize(QtCore.QSize(231, 101))
        self.frame_theme_2.setStyleSheet("QFrame{\n"
" border:2px solid;\n"
"    border-color: rgb(5, 32, 56);\n"
"    background-color: rgb(36,38,58);\n"
"border-radius:10px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"outline: 0px solid gray;            \n"
"/*border:1px solid #eeeeee;*/            \n"
"color:rgb(145,151,163);\n"
"selection-color:white;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei UI;            \n"
"background-color:rgb(18,26,39);\n"
"selection-background-color:rgb(33,41,54);\n"
"border-top-radius:0px;\n"
"border-bottom-radius:10px;\n"
"}")
        self.frame_theme_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_theme_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_theme_2.setObjectName("frame_theme_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_theme_2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_label = QtWidgets.QLabel(self.frame_theme_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_label.sizePolicy().hasHeightForWidth())
        self.label_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_label.setFont(font)
        self.label_label.setStyleSheet("QLabel{\n"
"border:none;\n"
"color:#598FDC;\n"
"}")
        self.label_label.setObjectName("label_label")
        self.verticalLayout_19.addWidget(self.label_label, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.frame_selecttheme_2 = QtWidgets.QFrame(self.frame_theme_2)
        self.frame_selecttheme_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_selecttheme_2.setStyleSheet("QFrame{border:none;\n"
"}")
        self.frame_selecttheme_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_selecttheme_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_selecttheme_2.setLineWidth(0)
        self.frame_selecttheme_2.setObjectName("frame_selecttheme_2")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_selecttheme_2)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.comboBox_label = QtWidgets.QComboBox(self.frame_selecttheme_2)
        self.comboBox_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_label.sizePolicy().hasHeightForWidth())
        self.comboBox_label.setSizePolicy(sizePolicy)
        self.comboBox_label.setMinimumSize(QtCore.QSize(103, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.comboBox_label.setFont(font)
        self.comboBox_label.setMouseTracking(False)
        self.comboBox_label.setTabletTracking(False)
        self.comboBox_label.setStyleSheet("\n"
"QComboBox {\n"
"    border: 0px solid;\n"
"    border-bottom: 2px solid;\n"
"    border-color: #598FDC;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 1px 10px 1px 3px;\n"
"    min-width: 6em;\n"
"    background-color: rgb(57, 63, 103);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    /*subcontrol-origin: padding;*/\n"
"    subcontrol-position: top right;\n"
"    width: 40px;\n"
"    height: 39px;\n"
"    border: 0px solid;\n"
"    \n"
"    border-radius: 5px; /* same radius as the QComboBox */\n"
"}\n"
"QComboBox::drop-down:pressed,QComboBox::drop-down:hover {\n"
"    background-color: rgb(38, 43, 85);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    image: url(:/图标/下拉选择.png);\n"
"width: 100px;\n"
"height:25px;\n"
"    \n"
"}\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"outline: 0px solid gray;            \n"
"border:0px solid #eeeeee;            \n"
"color:rgb(145,151,163);\n"
"selection-color:white;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei UI;            \n"
"background-color:rgb(18,26,39);\n"
"selection-background-color:rgb(33,41,54);\n"
"}")
        self.comboBox_label.setEditable(False)
        self.comboBox_label.setIconSize(QtCore.QSize(9, 9))
        self.comboBox_label.setObjectName("comboBox_label")
        self.comboBox_label.addItem("")
        self.comboBox_label.addItem("")
        self.horizontalLayout_20.addWidget(self.comboBox_label)
        self.verticalLayout_19.addWidget(self.frame_selecttheme_2, 0, QtCore.Qt.AlignBottom)
        self.gridLayout.addWidget(self.frame_theme_2, 1, 1, 1, 1)
        self.frame_anifont_2 = QtWidgets.QFrame(self.frame_settingleft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_anifont_2.sizePolicy().hasHeightForWidth())
        self.frame_anifont_2.setSizePolicy(sizePolicy)
        self.frame_anifont_2.setMinimumSize(QtCore.QSize(231, 101))
        self.frame_anifont_2.setStyleSheet("QFrame{\n"
" border:2px solid;\n"
"    border-color: rgb(5, 32, 56);\n"
"    background-color: rgb(36,38,58);\n"
"border-radius:10px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"outline: 0px solid gray;            \n"
"/*border:1px solid #eeeeee;*/            \n"
"color:rgb(145,151,163);\n"
"selection-color:white;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei UI;            \n"
"background-color:rgb(18,26,39);\n"
"selection-background-color:rgb(33,41,54);\n"
"border-top-radius:0px;\n"
"border-bottom-radius:10px;\n"
"}")
        self.frame_anifont_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_anifont_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_anifont_2.setObjectName("frame_anifont_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_anifont_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_anifont_2 = QtWidgets.QLabel(self.frame_anifont_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_anifont_2.sizePolicy().hasHeightForWidth())
        self.label_anifont_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_anifont_2.setFont(font)
        self.label_anifont_2.setStyleSheet("QLabel{\n"
"border:none;\n"
"color:#598FDC;\n"
"}")
        self.label_anifont_2.setObjectName("label_anifont_2")
        self.verticalLayout_13.addWidget(self.label_anifont_2)
        self.frame_selectanifont_2 = QtWidgets.QFrame(self.frame_anifont_2)
        self.frame_selectanifont_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_selectanifont_2.setStyleSheet("QFrame{border:none;\n"
"}")
        self.frame_selectanifont_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_selectanifont_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_selectanifont_2.setLineWidth(0)
        self.frame_selectanifont_2.setObjectName("frame_selectanifont_2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_selectanifont_2)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.comboBox_fontcor = QtWidgets.QComboBox(self.frame_selectanifont_2)
        self.comboBox_fontcor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_fontcor.sizePolicy().hasHeightForWidth())
        self.comboBox_fontcor.setSizePolicy(sizePolicy)
        self.comboBox_fontcor.setMinimumSize(QtCore.QSize(103, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.comboBox_fontcor.setFont(font)
        self.comboBox_fontcor.setMouseTracking(False)
        self.comboBox_fontcor.setTabletTracking(False)
        self.comboBox_fontcor.setStyleSheet("\n"
"QComboBox {\n"
"    border: 0px solid;\n"
"    border-bottom: 2px solid;\n"
"    border-color: #598FDC;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 1px 10px 1px 3px;\n"
"    min-width: 6em;\n"
"    background-color: rgb(57, 63, 103);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    /*subcontrol-origin: padding;*/\n"
"    subcontrol-position: top right;\n"
"    width: 40px;\n"
"    height: 39px;\n"
"    border: 0px solid;\n"
"    \n"
"    border-radius: 5px; /* same radius as the QComboBox */\n"
"}\n"
"QComboBox::drop-down:pressed,QComboBox::drop-down:hover {\n"
"    background-color: rgb(38, 43, 85);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    image: url(:/图标/下拉选择.png);\n"
"width: 100px;\n"
"height:25px;\n"
"    \n"
"}\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"outline: 0px solid gray;            \n"
"border:0px solid #eeeeee;            \n"
"color:rgb(145,151,163);\n"
"selection-color:white;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei UI;            \n"
"background-color:rgb(18,26,39);\n"
"selection-background-color:rgb(33,41,54);\n"
"}")
        self.comboBox_fontcor.setEditable(False)
        self.comboBox_fontcor.setIconSize(QtCore.QSize(9, 9))
        self.comboBox_fontcor.setObjectName("comboBox_fontcor")
        self.comboBox_fontcor.addItem("")
        self.comboBox_fontcor.addItem("")
        self.comboBox_fontcor.addItem("")
        self.comboBox_fontcor.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox_fontcor)
        self.verticalLayout_13.addWidget(self.frame_selectanifont_2, 0, QtCore.Qt.AlignBottom)
        self.gridLayout.addWidget(self.frame_anifont_2, 1, 2, 1, 1)
        self.frame_anifont_4 = QtWidgets.QFrame(self.frame_settingleft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_anifont_4.sizePolicy().hasHeightForWidth())
        self.frame_anifont_4.setSizePolicy(sizePolicy)
        self.frame_anifont_4.setMinimumSize(QtCore.QSize(231, 101))
        self.frame_anifont_4.setStyleSheet("QFrame{\n"
" border:2px solid;\n"
"    border-color: rgb(5, 32, 56);\n"
"    background-color: rgb(36,38,58);\n"
"border-radius:10px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"outline: 0px solid gray;            \n"
"/*border:1px solid #eeeeee;*/            \n"
"color:rgb(145,151,163);\n"
"selection-color:white;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei UI;            \n"
"background-color:rgb(18,26,39);\n"
"selection-background-color:rgb(33,41,54);\n"
"border-top-radius:0px;\n"
"border-bottom-radius:10px;\n"
"}")
        self.frame_anifont_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_anifont_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_anifont_4.setObjectName("frame_anifont_4")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_anifont_4)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_anifont_4 = QtWidgets.QLabel(self.frame_anifont_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_anifont_4.sizePolicy().hasHeightForWidth())
        self.label_anifont_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_anifont_4.setFont(font)
        self.label_anifont_4.setStyleSheet("QLabel{\n"
"border:none;\n"
"color:#598FDC;\n"
"}")
        self.label_anifont_4.setObjectName("label_anifont_4")
        self.verticalLayout_18.addWidget(self.label_anifont_4)
        self.frame_selectanifont_5 = QtWidgets.QFrame(self.frame_anifont_4)
        self.frame_selectanifont_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_selectanifont_5.setStyleSheet("QFrame{border:none;\n"
"}")
        self.frame_selectanifont_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_selectanifont_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_selectanifont_5.setLineWidth(0)
        self.frame_selectanifont_5.setObjectName("frame_selectanifont_5")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_selectanifont_5)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.comboBox_nodeshape = QtWidgets.QComboBox(self.frame_selectanifont_5)
        self.comboBox_nodeshape.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_nodeshape.sizePolicy().hasHeightForWidth())
        self.comboBox_nodeshape.setSizePolicy(sizePolicy)
        self.comboBox_nodeshape.setMinimumSize(QtCore.QSize(103, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.comboBox_nodeshape.setFont(font)
        self.comboBox_nodeshape.setMouseTracking(False)
        self.comboBox_nodeshape.setTabletTracking(False)
        self.comboBox_nodeshape.setStyleSheet("\n"
"QComboBox {\n"
"    border: 0px solid;\n"
"    border-bottom: 2px solid;\n"
"    border-color: #598FDC;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 1px 10px 1px 3px;\n"
"    min-width: 6em;\n"
"    background-color: rgb(57, 63, 103);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    /*subcontrol-origin: padding;*/\n"
"    subcontrol-position: top right;\n"
"    width: 40px;\n"
"    height: 39px;\n"
"    border: 0px solid;\n"
"    \n"
"    border-radius: 5px; /* same radius as the QComboBox */\n"
"}\n"
"QComboBox::drop-down:pressed,QComboBox::drop-down:hover {\n"
"    background-color: rgb(38, 43, 85);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    image: url(:/图标/下拉选择.png);\n"
"width: 100px;\n"
"height:25px;\n"
"    \n"
"}\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"outline: 0px solid gray;            \n"
"border:0px solid #eeeeee;            \n"
"color:rgb(145,151,163);\n"
"selection-color:white;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei UI;            \n"
"background-color:rgb(18,26,39);\n"
"selection-background-color:rgb(33,41,54);\n"
"}")
        self.comboBox_nodeshape.setEditable(False)
        self.comboBox_nodeshape.setIconSize(QtCore.QSize(9, 9))
        self.comboBox_nodeshape.setObjectName("comboBox_nodeshape")
        self.comboBox_nodeshape.addItem("")
        self.comboBox_nodeshape.addItem("")
        self.horizontalLayout_22.addWidget(self.comboBox_nodeshape)
        self.verticalLayout_18.addWidget(self.frame_selectanifont_5, 0, QtCore.Qt.AlignBottom)
        self.gridLayout.addWidget(self.frame_anifont_4, 2, 1, 1, 1)
        self.frame_anifont_3 = QtWidgets.QFrame(self.frame_settingleft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_anifont_3.sizePolicy().hasHeightForWidth())
        self.frame_anifont_3.setSizePolicy(sizePolicy)
        self.frame_anifont_3.setMinimumSize(QtCore.QSize(231, 101))
        self.frame_anifont_3.setStyleSheet("QFrame{\n"
" border:2px solid;\n"
"    border-color: rgb(5, 32, 56);\n"
"    background-color: rgb(36,38,58);\n"
"border-radius:10px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"outline: 0px solid gray;            \n"
"/*border:1px solid #eeeeee;*/            \n"
"color:rgb(145,151,163);\n"
"selection-color:white;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei UI;            \n"
"background-color:rgb(18,26,39);\n"
"selection-background-color:rgb(33,41,54);\n"
"border-top-radius:0px;\n"
"border-bottom-radius:10px;\n"
"}")
        self.frame_anifont_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_anifont_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_anifont_3.setObjectName("frame_anifont_3")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_anifont_3)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_anifont_3 = QtWidgets.QLabel(self.frame_anifont_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_anifont_3.sizePolicy().hasHeightForWidth())
        self.label_anifont_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_anifont_3.setFont(font)
        self.label_anifont_3.setStyleSheet("QLabel{\n"
"border:none;\n"
"color:#598FDC;\n"
"}")
        self.label_anifont_3.setObjectName("label_anifont_3")
        self.verticalLayout_17.addWidget(self.label_anifont_3)
        self.frame_selectanifont_3 = QtWidgets.QFrame(self.frame_anifont_3)
        self.frame_selectanifont_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_selectanifont_3.setStyleSheet("QFrame{border:none;\n"
"}")
        self.frame_selectanifont_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_selectanifont_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_selectanifont_3.setLineWidth(0)
        self.frame_selectanifont_3.setObjectName("frame_selectanifont_3")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_selectanifont_3)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.comboBox_nodecor = QtWidgets.QComboBox(self.frame_selectanifont_3)
        self.comboBox_nodecor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_nodecor.sizePolicy().hasHeightForWidth())
        self.comboBox_nodecor.setSizePolicy(sizePolicy)
        self.comboBox_nodecor.setMinimumSize(QtCore.QSize(103, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.comboBox_nodecor.setFont(font)
        self.comboBox_nodecor.setMouseTracking(False)
        self.comboBox_nodecor.setTabletTracking(False)
        self.comboBox_nodecor.setStyleSheet("\n"
"QComboBox {\n"
"    border: 0px solid;\n"
"    border-bottom: 2px solid;\n"
"    border-color: #598FDC;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 1px 10px 1px 3px;\n"
"    min-width: 6em;\n"
"    background-color: rgb(57, 63, 103);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    /*subcontrol-origin: padding;*/\n"
"    subcontrol-position: top right;\n"
"    width: 40px;\n"
"    height: 39px;\n"
"    border: 0px solid;\n"
"    \n"
"    border-radius: 5px; /* same radius as the QComboBox */\n"
"}\n"
"QComboBox::drop-down:pressed,QComboBox::drop-down:hover {\n"
"    background-color: rgb(38, 43, 85);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    image: url(:/图标/下拉选择.png);\n"
"width: 100px;\n"
"height:25px;\n"
"    \n"
"}\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"outline: 0px solid gray;            \n"
"border:0px solid #eeeeee;            \n"
"color:rgb(145,151,163);\n"
"selection-color:white;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei UI;            \n"
"background-color:rgb(18,26,39);\n"
"selection-background-color:rgb(33,41,54);\n"
"}")
        self.comboBox_nodecor.setEditable(False)
        self.comboBox_nodecor.setIconSize(QtCore.QSize(9, 9))
        self.comboBox_nodecor.setObjectName("comboBox_nodecor")
        self.comboBox_nodecor.addItem("")
        self.comboBox_nodecor.addItem("")
        self.comboBox_nodecor.addItem("")
        self.comboBox_nodecor.addItem("")
        self.horizontalLayout_19.addWidget(self.comboBox_nodecor)
        self.verticalLayout_17.addWidget(self.frame_selectanifont_3, 0, QtCore.Qt.AlignBottom)
        self.gridLayout.addWidget(self.frame_anifont_3, 2, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, 20, -1, 28)
        self.horizontalLayout_3.setSpacing(30)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_anifont = QtWidgets.QFrame(self.frame_settingleft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_anifont.sizePolicy().hasHeightForWidth())
        self.frame_anifont.setSizePolicy(sizePolicy)
        self.frame_anifont.setMinimumSize(QtCore.QSize(231, 101))
        self.frame_anifont.setStyleSheet("QFrame{\n"
" border:2px solid;\n"
"    border-color: rgb(5, 32, 56);\n"
"    background-color: rgb(36,38,58);\n"
"border-radius:10px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"outline: 0px solid gray;            \n"
"/*border:1px solid #eeeeee;*/            \n"
"color:rgb(145,151,163);\n"
"selection-color:white;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei UI;            \n"
"background-color:rgb(18,26,39);\n"
"selection-background-color:rgb(33,41,54);\n"
"border-top-radius:0px;\n"
"border-bottom-radius:10px;\n"
"}")
        self.frame_anifont.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_anifont.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_anifont.setObjectName("frame_anifont")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_anifont)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_anifont = QtWidgets.QLabel(self.frame_anifont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_anifont.sizePolicy().hasHeightForWidth())
        self.label_anifont.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_anifont.setFont(font)
        self.label_anifont.setStyleSheet("QLabel{\n"
"border:none;\n"
"color:#598FDC;\n"
"}")
        self.label_anifont.setObjectName("label_anifont")
        self.verticalLayout_11.addWidget(self.label_anifont)
        self.frame_selectanifont = QtWidgets.QFrame(self.frame_anifont)
        self.frame_selectanifont.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_selectanifont.setStyleSheet("QFrame{border:none;\n"
"}")
        self.frame_selectanifont.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_selectanifont.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_selectanifont.setLineWidth(0)
        self.frame_selectanifont.setObjectName("frame_selectanifont")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_selectanifont)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lineEdit_nodesize = QtWidgets.QLineEdit(self.frame_selectanifont)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nodesize.sizePolicy().hasHeightForWidth())
        self.lineEdit_nodesize.setSizePolicy(sizePolicy)
        self.lineEdit_nodesize.setMinimumSize(QtCore.QSize(103, 41))
        self.lineEdit_nodesize.setMaximumSize(QtCore.QSize(145, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_nodesize.setFont(font)
        self.lineEdit_nodesize.setStyleSheet("QLineEdit{ border: 0px solid;\n"
"    border-bottom: 2px solid;\n"
"    border-color: #598FDC;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 1px 10px 1px 3px;\n"
"    min-width: 6em;\n"
"    background-color: rgb(57, 63, 103);\n"
"    \n"
"    color: rgb(255, 255, 255);}")
        self.lineEdit_nodesize.setObjectName("lineEdit_nodesize")
        self.horizontalLayout_13.addWidget(self.lineEdit_nodesize)
        self.verticalLayout_11.addWidget(self.frame_selectanifont, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.frame_anifont)
        self.frame_anifont_6 = QtWidgets.QFrame(self.frame_settingleft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_anifont_6.sizePolicy().hasHeightForWidth())
        self.frame_anifont_6.setSizePolicy(sizePolicy)
        self.frame_anifont_6.setMinimumSize(QtCore.QSize(231, 101))
        self.frame_anifont_6.setStyleSheet("QFrame{\n"
" border:2px solid;\n"
"    border-color: rgb(5, 32, 56);\n"
"    background-color: rgb(36,38,58);\n"
"border-radius:10px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"outline: 0px solid gray;            \n"
"/*border:1px solid #eeeeee;*/            \n"
"color:rgb(145,151,163);\n"
"selection-color:white;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei UI;            \n"
"background-color:rgb(18,26,39);\n"
"selection-background-color:rgb(33,41,54);\n"
"border-top-radius:0px;\n"
"border-bottom-radius:10px;\n"
"}")
        self.frame_anifont_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_anifont_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_anifont_6.setObjectName("frame_anifont_6")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_anifont_6)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_anifont_6 = QtWidgets.QLabel(self.frame_anifont_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_anifont_6.sizePolicy().hasHeightForWidth())
        self.label_anifont_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_anifont_6.setFont(font)
        self.label_anifont_6.setStyleSheet("QLabel{\n"
"border:none;\n"
"color:#598FDC;\n"
"}")
        self.label_anifont_6.setObjectName("label_anifont_6")
        self.verticalLayout_23.addWidget(self.label_anifont_6, 0, QtCore.Qt.AlignTop)
        self.frame_selectanifont_4 = QtWidgets.QFrame(self.frame_anifont_6)
        self.frame_selectanifont_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_selectanifont_4.setStyleSheet("QFrame{border:none;\n"
"}")
        self.frame_selectanifont_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_selectanifont_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_selectanifont_4.setLineWidth(0)
        self.frame_selectanifont_4.setObjectName("frame_selectanifont_4")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_selectanifont_4)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.lineEdit_vespeed = QtWidgets.QLineEdit(self.frame_selectanifont_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_vespeed.sizePolicy().hasHeightForWidth())
        self.lineEdit_vespeed.setSizePolicy(sizePolicy)
        self.lineEdit_vespeed.setMinimumSize(QtCore.QSize(103, 41))
        self.lineEdit_vespeed.setMaximumSize(QtCore.QSize(145, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_vespeed.setFont(font)
        self.lineEdit_vespeed.setStyleSheet("QLineEdit{ border: 0px solid;\n"
"    border-bottom: 2px solid;\n"
"    border-color: #598FDC;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 1px 10px 1px 3px;\n"
"    min-width: 6em;\n"
"    background-color: rgb(57, 63, 103);\n"
"    \n"
"    color: rgb(255, 255, 255);}")
        self.lineEdit_vespeed.setObjectName("lineEdit_vespeed")
        self.horizontalLayout_21.addWidget(self.lineEdit_vespeed)
        self.verticalLayout_23.addWidget(self.frame_selectanifont_4, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.frame_anifont_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.pushButton_check = QtWidgets.QPushButton(self.frame_settingleft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_check.sizePolicy().hasHeightForWidth())
        self.pushButton_check.setSizePolicy(sizePolicy)
        self.pushButton_check.setMinimumSize(QtCore.QSize(65, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_check.setFont(font)
        self.pushButton_check.setStyleSheet("QPushButton {    \n"
"    border: 2px solid;\n"
"    border-color: #598FDC;\n"
"    border-radius: 6px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(57, 63, 103);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(38, 43, 85);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(33, 33, 33);\n"
"}")
        self.pushButton_check.setCheckable(True)
        self.pushButton_check.setChecked(False)
        self.pushButton_check.setObjectName("pushButton_check")
        self.verticalLayout_2.addWidget(self.pushButton_check, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout_15.addWidget(self.frame_settingleft)
        self.stackedWidget.addWidget(self.page_settings)
        self.horizontalLayout_8.addWidget(self.stackedWidget)
        self.frame_2 = QtWidgets.QFrame(self.frame_down)
        self.frame_2.setMinimumSize(QtCore.QSize(14, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_8.addWidget(self.frame_2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_3 = QtWidgets.QFrame(self.frame_down)
        self.frame_3.setMinimumSize(QtCore.QSize(20, 14))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_11.addWidget(self.frame_3)
        self.frame_6 = QtWidgets.QFrame(self.frame_down)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(14, 14))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_11.addWidget(self.frame_6)
        self.verticalLayout_16.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_14.addLayout(self.verticalLayout_16)
        self.verticalLayout_15.addWidget(self.frame_down)
        self.horizontalLayout_16.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.comboBox_nodeshape.setCurrentIndex(0)
        self.pushButton_close.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_min.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_view.setText(_translate("MainWindow", "  动画浏览"))
        self.pushButton_settings.setText(_translate("MainWindow", "  设置       "))
        self.label_node.setText(_translate("MainWindow", "节点设置"))
        self.pushButton_vector.setText(_translate("MainWindow", "Vector"))
        self.pushButton_stack.setText(_translate("MainWindow", "Stack"))
        self.pushButton_heap.setText(_translate("MainWindow", "Heap"))
        self.pushButton_tree.setText(_translate("MainWindow", "Tree"))
        self.pushButton_matrix.setText(_translate("MainWindow", "Matrix"))
        self.label_language_2.setText(_translate("MainWindow", "整体样式"))
        self.label_theme.setText(_translate("MainWindow", "主题"))
        self.comboBox_theme.setItemText(0, _translate("MainWindow", "深色模式"))
        self.comboBox_theme.setItemText(1, _translate("MainWindow", "浅色模式"))
        self.label_label.setText(_translate("MainWindow", "动画说明"))
        self.comboBox_label.setItemText(0, _translate("MainWindow", "否"))
        self.comboBox_label.setItemText(1, _translate("MainWindow", "是"))
        self.label_anifont_2.setText(_translate("MainWindow", "动画字体颜色"))
        self.comboBox_fontcor.setItemText(0, _translate("MainWindow", "黑色"))
        self.comboBox_fontcor.setItemText(1, _translate("MainWindow", "红色"))
        self.comboBox_fontcor.setItemText(2, _translate("MainWindow", "绿色"))
        self.comboBox_fontcor.setItemText(3, _translate("MainWindow", "蓝色"))
        self.label_anifont_4.setText(_translate("MainWindow", "节点形状"))
        self.comboBox_nodeshape.setItemText(0, _translate("MainWindow", "圆形"))
        self.comboBox_nodeshape.setItemText(1, _translate("MainWindow", "方形"))
        self.label_anifont_3.setText(_translate("MainWindow", "节点颜色"))
        self.comboBox_nodecor.setItemText(0, _translate("MainWindow", "黑色"))
        self.comboBox_nodecor.setItemText(1, _translate("MainWindow", "红色"))
        self.comboBox_nodecor.setItemText(2, _translate("MainWindow", "绿色"))
        self.comboBox_nodecor.setItemText(3, _translate("MainWindow", "蓝色"))
        self.label_anifont.setText(_translate("MainWindow", "动画节点大小"))
        self.lineEdit_nodesize.setText(_translate("MainWindow", "60"))
        self.label_anifont_6.setText(_translate("MainWindow", "动画速度"))
        self.lineEdit_vespeed.setText(_translate("MainWindow", "50"))
        self.pushButton_check.setText(_translate("MainWindow", "确认"))
import res_rc
